Develop
JamesDeGreese/ya_golang_diploma pull request #1
Opened 2022-04-17 05:01 UTC by JamesDeGreese

2022-04-26 22:09 UTC, blattaria7 commented on internal/http/handlers.go
> +	return u.(entities.User)
приводя интерфейс к типу всегда нужно проверять на ошибку, иначе можно получить панику

```go
user, ok := u.(entities.User)
	if !ok{
		// ...
	}
	
	return user
```

2022-04-26 22:15 UTC, blattaria7 commented on internal/http/handlers.go
> +	res := make([]Withdraw, 0)
если мы можем предположить каким будет размер массива, стоит задавать ему размер при инициализации) почему так стоит делать написано [тут в главе _Выделяйте ёмкость для среза с помощью make, чтобы избежать перераспределения_](https://temofeev.ru/info/articles/prostye-metody-optimizatsii-programm-go/)

а тут он равен размеру withdrawals, тк res увеличивается с каждой итерацией цикла )

2022-04-26 22:26 UTC, blattaria7 requested changes
Привет!

По самому коду все прекрасно! 

Но по архитектуре есть ряд замечаний:
1. Саму инициализацию коннекшена надо проинициализировать в самом начале.
2. Для каждого репозитория (у тебя их несколько) завести свой конструктор и передавать туда этот коннекшен
3. И уже сами репозитории все передавать на уровень с бизнес-логикой (в твоей случае с хендлерами) и работать уже по утиной типизации с ними, объявив для них интерфейсы в самом начале файла с хендлерами
4. И тоже самое сделать для accrual service.
Сейчас получается так, что репозитории это разные слои и их все нужно инициализировать в каждом хендлере, а это противоречит DI проекта.

Нужно внести эти доработки и я смогу принять проект =)

2022-05-04 07:39 UTC, blattaria7 commented on internal/http/router.go
> +	logger, _ := zap.NewProduction()
инициализацию логгера стоит вынести в main и передавать в SetupRouter
и обязательно стоит обработать ошибку - игнорирование ошибки это антипаттерн)

2022-05-04 07:39 UTC, blattaria7 commented on internal/http/middleware.go
> +			}
тут тоже стоит обработать ошибку

2022-05-04 07:44 UTC, blattaria7 commented on internal/http/router.go
> +	logger, _ := zap.NewProduction()
можно просто залоггировать 
или вынести инициализацию в main и запаниковать

2022-05-04 07:45 UTC, blattaria7 approved these changes
Все отлично, ставлю аппрув :)
Поздравляю с успешным прохождением курса 🥳

Рекомендую поправить 2 небольших замечания перед мерджом.

2022-05-05 05:14 UTC, JamesDeGreese commented on internal/http/middleware.go
> +			}
ok

2022-05-05 06:23 UTC, merged